version: '3.7'
services:
  posterr-db:
    container_name: postgres_posterr
    image: postgres:11.5
    environment:
      POSTGRES_DB: posterr
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - network-posterr

  posterr-app:
    image: posterr-app:dev
    container_name: posterr-app-dev
    build:
      context: ../..
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://posterr-db:5432/posterr
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - "posterr-db"
    networks:
      - network-posterr

networks:
  network-posterr:
    driver: bridge
